-- Fill columns skipped by CREATE TABLE IF NOT EXISTS on partially applied v64 schema.

ALTER TABLE "security_events" ADD COLUMN IF NOT EXISTS "ts" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "security_events" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT '';
ALTER TABLE "security_events" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "security_events" ADD COLUMN IF NOT EXISTS "severity" TEXT NOT NULL DEFAULT 'info';
ALTER TABLE "security_events" ADD COLUMN IF NOT EXISTS "detail" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "security_events" ADD COLUMN IF NOT EXISTS "user_agent" TEXT;

ALTER TABLE "password_history" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "password_history" ADD COLUMN IF NOT EXISTS "password_hash" TEXT;
ALTER TABLE "password_history" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "consent_records" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "consent_records" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "consent_records" ADD COLUMN IF NOT EXISTS "version" TEXT;
ALTER TABLE "consent_records" ADD COLUMN IF NOT EXISTS "at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "consent_records" ADD COLUMN IF NOT EXISTS "ip" TEXT;
ALTER TABLE "consent_records" ADD COLUMN IF NOT EXISTS "withdrawn" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "consent_records" ADD COLUMN IF NOT EXISTS "reason" TEXT;

ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "ref" TEXT;
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "kind" TEXT;
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "subject" TEXT;
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "client_id" VARCHAR(4);
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "raised_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "raised_by" TEXT;
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "due" DATE;
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "note" TEXT NOT NULL DEFAULT '';
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'open';
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "closed_at" TIMESTAMP(3);
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "closed_by" TEXT;
ALTER TABLE "dsr_requests" ADD COLUMN IF NOT EXISTS "outcome" TEXT NOT NULL DEFAULT '';

ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "ref" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "severity" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "detected_at" DATE;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "raised_by" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "raised_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "summary" TEXT NOT NULL DEFAULT '';
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "affected" TEXT NOT NULL DEFAULT '';
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'open';
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "contained_at" TIMESTAMP(3);
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "closed_at" TIMESTAMP(3);
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "closed_by" TEXT;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "root_cause" TEXT NOT NULL DEFAULT '';
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "action" TEXT NOT NULL DEFAULT '';
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "reportable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "incidents" ADD COLUMN IF NOT EXISTS "reported_at" TIMESTAMP(3);

ALTER TABLE "access_reviews" ADD COLUMN IF NOT EXISTS "ref" TEXT;
ALTER TABLE "access_reviews" ADD COLUMN IF NOT EXISTS "started_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "access_reviews" ADD COLUMN IF NOT EXISTS "started_by" TEXT;
ALTER TABLE "access_reviews" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'open';
ALTER TABLE "access_reviews" ADD COLUMN IF NOT EXISTS "closed_at" TIMESTAMP(3);
ALTER TABLE "access_reviews" ADD COLUMN IF NOT EXISTS "closed_by" TEXT;

ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "review_id" TEXT;
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "role" TEXT;
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "client_id" TEXT;
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "site_ids" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "factory_ids" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "last_login_at" TIMESTAMP(3);
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "decision" TEXT;
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "note" TEXT NOT NULL DEFAULT '';
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "decided_at" TIMESTAMP(3);
ALTER TABLE "access_review_lines" ADD COLUMN IF NOT EXISTS "decided_by" TEXT;

ALTER TABLE "disposal_records" ADD COLUMN IF NOT EXISTS "ref" TEXT;
ALTER TABLE "disposal_records" ADD COLUMN IF NOT EXISTS "kind" TEXT;
ALTER TABLE "disposal_records" ADD COLUMN IF NOT EXISTS "describes" TEXT;
ALTER TABLE "disposal_records" ADD COLUMN IF NOT EXISTS "method" TEXT;
ALTER TABLE "disposal_records" ADD COLUMN IF NOT EXISTS "at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "disposal_records" ADD COLUMN IF NOT EXISTS "by" TEXT;
ALTER TABLE "disposal_records" ADD COLUMN IF NOT EXISTS "approved_by" TEXT NOT NULL DEFAULT '';
ALTER TABLE "disposal_records" ADD COLUMN IF NOT EXISTS "note" TEXT NOT NULL DEFAULT '';

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password_set_at" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "must_reset" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "mfa_secret" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "mfa_at" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_login_at" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "failed_login_count" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "locked_until" TIMESTAMP(3);

ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "seq" INTEGER;
ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "prev_hash" TEXT NOT NULL DEFAULT 'GENESIS';
ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "hash" TEXT NOT NULL DEFAULT '';
